# @package _global_

fps: 50

env:
  name: lowcostrobot
  fps: ${fps}
  handle: LerobotCube-v0
  state_dim: 6
  action_dim: 6
  task: PushCube

  gym:
    render_mode: human
    max_episode_steps: 200
    # actions_in_degrees: true
    reward_type: 'dense'

calibration:
  homing_offset: [0, 0, 0, 0, 0, -280] 
  drive_mode: [1, 1, 0, 0, 1, 0]
  start_pos: [0, 0, 0, 0, 0, -131]
  end_pos: [-1024, -1024, 1024, 1024, -1024, 1304]
  calib_mode: ["DEGREE", "DEGREE", "DEGREE", "DEGREE", "DEGREE", "DEGREE"]
  motor_names: ["shoulder_pan", "shoulder_lift", "elbow_flex", "wrist_flex", "wrist_roll", "gripper"]

eval:
  use_async_envs: false

state_keys:
  observation.state: 'arm_qpos'
  observation.velocity: 'arm_qvel'